### ISSUE TITLE
Fund wallet error

### ISSUE THREAD

**Issue by PetrJoe** [SirDamis/Django-Ewallet#1]
<html>
<body>

Request Method: | POST
-- | --
http://127.0.0.1:8000/wallet/fund-wallet/
3.2.13
JSONDecodeError
[Errno Expecting value] <html> <head><title>403 Forbidden</title></head> <body> <center><h1>403 Forbidden</h1></center> </body> </html>

</body>
</html>

**Comment by SirDamis** [comment]
@PetrJoe It was due to Flutterwave's recent feature. Only whitelisted IP address can access some endpoints. You can check this [link](https://forum.flutterwave.com/t/i-got-403-forbidden-error-when-try-to-transfer-using-api-https-api-flutterwave-com-v3-transfers/1104/2)
